### ISSUE TITLE
[BUG] Wrong behavior on iOS

### ISSUE THREAD

**Issue by fortunella** [jrquick17/ionic4-auto-complete#59]
The component works fine, but the behavior on iOS is still not as expected and different from Android.

This behavior is still there in 2.5.1. I can reproduce it with my iPhone X device as well as with the simulator of an iPhone 11 in Xcode 11.3.1.

When I tap an item in the open list on iOS, in a first step the keyboard is closed. Then I have to tap the item again to be taken into the text field. On Android this is done in one step as I would expect.

This is my code:
```
<ion-auto-complete formControlName="building" #building [dataProvider]="buildingService"
                                [options]="{searchIcon: '', debounce: 100, placeholder: placeholder}"
                                (itemSelected)="changeBuilding()" (autoBlur)="changeBuilding()"></ion-auto-complete>
```

I recorded a short video on the iPhone X to show the behavior. What you can see is that in a first step the keyboard closes and then in a second step the selected item is taken into the text field. As a result I always have to tap an item twice to select it.

Please let me know if I can support you with further info and so on.

![ionic4-autocomplete](https://user-images.githubusercontent.com/17113047/75138532-be1b0800-56ea-11ea-8c16-bd578ec527a3.gif)

**Comment by jrquick17** [comment]
Thanks for the help @fortunella. When I have more free time I will investigate further.

**Comment by fortunella** [comment]
I checked if the problem is still there in version 2.6.0. Unfortunately yes.

Please, let me know if I can support you, myabe by testing on an iPhone X or in any other way.

**Comment by Grocione** [comment]
The problem occurs when you tap on the text, if you press the div area it doesn't happen.

**Comment by fortunella** [comment]
OK, but that's a bug then, because every "normal" end user expects to tap on the text.

**Comment by Grocione** [comment]
> OK, but that's a bug then, because every "normal" end user expects to tap on the text.

I agree, my comment wants to add a useful detail to the resolution

**Comment by jrquick17** [comment]
A few bugs have been fixed could someone verify if this is still an issue in the latest (^2.7.1).

**Comment by Grocione** [comment]
> A few bugs have been fixed could someone verify if this is still an issue in the latest (^2.7.1).

Thanks, issue resolved!

**Comment by fortunella** [comment]
I can also confirm that this issue is fixed. Thanks a lot!

**Comment by jrquick17** [comment]
Thanks for all for ya'lls help in reportinggro, reproducing, and testing @fortunella @Grocione

**Comment by mgreg89** [comment]
I can still reproduce this issue with version 2.8.0.

My observations:

- mouseenter event is fired when touching the title, no click or tap event
- happens on own ng-template (not tested with default template)
- on second tap on title the item is selected (tap or click event fired)
- same behaviour on browser (chrome tested)
- seems to be a bug in angular: https://stackoverflow.com/questions/53514824/angular-6-mouseenter-is-fired-instead-click-event-on-tap
- tested with angular 8.2.14

My working workaround for the moment:
I'm wrapping the template in a div, such that I can trigger handleTapSelect method (which is normally called on itemSelected event).
In HTML:
```
<ng-template #defaultTemplate let-attrs="attrs">
    <div (mouseenter)="onMouseEnter($event, attrs.data)">
        <ng-template [ngTemplateOutlet]="template"
                     [ngTemplateOutletContext]="{
                            attrs: attrs
                         }">
        </ng-template>
    </div>
</ng-template>
<ion-auto-complete #autoComplete
                   ...
                   [template]="defaultTemplate"
                   ...>
</ion-auto-complete>
```

In Component:
```
onMouseEnter(event, seletion) {
	if (!this.onBrowser()) {
		this.autoComplete.handleSelectTap(event, seletion);
	} else if(event.buttons === 1){
		this.autoComplete.handleSelectTap(event, seletion);
	}
}
```
Note that on browser we can / should check event.buttons, which will be 1 on click (beware: even on right click).

**Comment by Shmarkus** [comment]
can confirm that mgreg89 solution worked for iOS build with Ionic 5.29.0 Angular 10.2.2 and ionic4-auto-complete 2.9.4

**Comment by jrquick17** [comment]
A new release (v2.9.6) has been added with a possible solution for this. As I cannot test this, can anyone confirm it is fixed in v2.9.6+ ? 🤞

**Comment by Shmarkus** [comment]
I tested 2.9.8 within an iOS emulator and it seems to be working as expected!

**Comment by jrquick17** [comment]
Great news! Feel free to open again otherwise.
