### ISSUE TITLE
itemSelected click event propagates to another element

### ISSUE THREAD

**Issue by stefan12r** [jrquick17/ionic4-auto-complete#9]
When you click to select an element the click event propagates to the element that was originally in the place of the click before the list was shown

**Comment by jrquick17** [comment]
Hey @stefan12r this has been fixed in version `1.8.0`

**Comment by sagits** [comment]
Hi @jrquick17, I still have this problem, tested on 1.8.8 and 1.9.0. I have tried to use Jquery to preventDefault and stopPropagation on ul click, but no success. Can you give me any advice please? (i have a button below the auto-complete) Thanks in advance.
